### ISSUE TITLE
files.New() returns an unexported type

### ISSUE THREAD

**Issue by ncw** [dropbox/dropbox-sdk-go-unofficial#11]
This applies to all the sub modules, but I'll just use `files` as an example.

`files.New(config)` returns  `*files.apiImpl`

Since `apiImpl` starts with a lower case letter it is private. In an external module you can't define a variable of type `*files.apiImpl`, which means that you can't pass the result from `files.New()` to a function, or put it in a structure which makes re-using these handles very difficult.

Is this deliberate?

Is running files.New() so cheap that you just do that whenever you want a new handle?

I notice that in the commands in dbxcli they are all written in a single function.

My preference would be for the `apiImpl` to become public `APIClient`.

Since the `apiImpl` is just a type alias of a public type this doesn't lose you any type security

```
type apiImpl dropbox.Context
```

**Comment by ncw** [comment]
After reading more code, I've discovered that the canonical type I should be using is the `files.Client` interface which makes perfect sense!

Apologies for the noise ;-)

**Comment by diwakergupta** [comment]
I love issues that self-resolve! I'm always open to feedback on how we can improve the API/interface though, so keep it coming :)

**Comment by ncw** [comment]
@diwakergupta wrote
>  love issues that self-resolve! I'm always open to feedback on how we can improve the API/interface though, so keep it coming :)

he he!
