### ISSUE TITLE
Make verbose output target configurable?

### ISSUE THREAD

**Issue by DexterHaslem** [dropbox/dropbox-sdk-go-unofficial#16]
Hi,
I see all the verbose outputs use the default log `log.Printf` and friends. I need to keep track of all outbound traffic, so these logs are useful, and I'm able to capture them with `log.SetOutput()` no problem.
 It can be problematic when I am already using the global default log methods.

I understand this code is generated with stone, so my question is if it would be easy to set a custom logger via the api itself instead of having to wedge a different writer behind the default logger?

**Comment by diwakergupta** [comment]
@DexterHaslem main constraint here is dependencies: if the Go standard library had a more flexible logger interface, or allowed pluggable loggers, this wouldn't be an issue. As it stands, my only option is to use the `log` package, or introduce yet another SDK-specific abstraction and I've preferred the former. If you have better suggestions, I'm all ears!

**Comment by DexterHaslem** [comment]
That is an understandable concern, let me clarify. Still using the standard go `log` api is fine, I was just after a way to change it from the global logger. I forked and did this internally:

``` 
// sdk.go
type Config struct {
        // .... 

	// Enable verbose logging in SDK
	Verbose bool
	// Verbose logging target
	Logger *log.Logger
        // ... 
}
```

If logger is not provided, it could be set to default global logger (stderr) like it currently is setup.
I then changed all verbose `log.Printf()` invocations in clients to `dbx.Logger.Printf()`

If something like this looks acceptable to you, I'd be willing look into changing the generator to create this.

If it helps, the motivation was 2fold: saving logs to file, and having multiple clients log at the same time

**Comment by diwakergupta** [comment]
Ah yes, that makes sense. I welcome PRs if you want to take a stab! :) Otherwise I'll try to get to it sometime this week.

**Comment by diwakergupta** [comment]
We could model after the AWS SDK, but it might be overkill. I really wish Go had something built-in :(

https://github.com/aws/aws-sdk-go/blob/master/aws/logger.go

**Comment by DexterHaslem** [comment]
Thanks for the feedback, I will work on a PR. I will do something simple w/o log levels, just changing logger as above to start with!

**Comment by ncw** [comment]
This issue should be closed now the PR has been merged.
