### ISSUE TITLE
Timestamps

### ISSUE THREAD

**Issue by hexasoftware** [dropbox/dropbox-sdk-go-unofficial#17]
Issue: 
Error in call to API function "files/upload": HTTP header "Dropbox-API-Arg": client_modified: time data '2017-07-15T16:09:11.172473155Z' does not match format '%Y-%m-%dT%H:%M:%SZ' 

Problematic function [files/client.go:3064](https://github.com/dropbox/dropbox-sdk-go-unofficial/blob/master/dropbox/files/client.go#L3064-L3072)

Go timestamps vs dropbox

in some structures such as CommitInfo # [files/types.go:220](https://github.com/dropbox/dropbox-sdk-go-unofficial/blob/master/dropbox/files/types.go#L220) uses go time structs which are serialized as shown above (RFC3339 or most commonly used in JSON/Javascript as it seems json does not specify a time format).

I'm not sure if i'm doing something wrong here but some solutions would be

* dropbox would 'change' to fully support rfc3339,
* custom type based on time.Time implementing json marshaler interface

**Comment by diwakergupta** [comment]
@hexasoftware thanks for the report. Can you include a full stack trace, along with sample code that you are using to issue the request? That will help me repro and debug. Thanks!

**Comment by diwakergupta** [comment]
I think I know what might be going on here. The Dropbox API expects UTC timestamps and doesn't support fractional seconds (https://github.com/dropbox/dropbox-api-spec/blob/master/common.stone#L3). You can see how `dbxcli` supplies the timestamp here: https://github.com/dropbox/dbxcli/blob/master/cmd/put.go#L102  Basically something like this should work:

```go
commitInfo.ClientModified = time.Now().UTC().Round(time.Second)
```

Please reopen if this doesn't fix your issue
