### ISSUE TITLE
Oauth flow using the standard oauth2 lib doesn't seem to work

### ISSUE THREAD

**Issue by joncalhoun** [dropbox/dropbox-sdk-go-unofficial#2]
I've mostly been learning go while using this SDK, so it is very possible I am doing something wrong, but on the off chance you can help I am posting here.

It doesn't seem like the dropbox oauth flow works with the oauth2 library out of the box. From what I can tell, it looks like the `/oauth2/authorize` endpoint works fine, but the `/oauth2/token` endpoint expects some params that aren't provided by default, and I have no idea how to tell the `Exchange` method of `oauth2.Config` to pass in extra params.

I can get around this by writing some custom code, but I was just wondering if you had any better suggestions. Thanks!

**Comment by smarx** [comment]
I'm not sure this question relates to this particular library, so it may be better moved to another forum, but here's a working app that pretty much just follows the example in the [`golang.org/x/oauth2` library docs](https://godoc.org/golang.org/x/oauth2#example-Config). I'm curious what parameters you think are missing from the call to `/oauth2/token` and why you think that's the issue?

```
package main

import "bytes"
import "fmt"
import "golang.org/x/oauth2"
import "io/ioutil"
import "encoding/json"
import "log"

func main() {
	conf := &oauth2.Config {
		ClientID: "<REDACTED>",
		ClientSecret: "<REDACTED>",
		Scopes: nil,
		Endpoint: oauth2.Endpoint {
			AuthURL: "https://www.dropbox.com/oauth2/authorize",
			TokenURL: "https://api.dropboxapi.com/oauth2/token",
		},
	}

	url := conf.AuthCodeURL("use-a-real-state-here")
	fmt.Printf("Visit this URL: %v\n", url)
	fmt.Print("Enter the access code: ")

	var code string
	if _, err := fmt.Scan(&code); err != nil {
		log.Fatal(err)
	}
	tok, err := conf.Exchange(oauth2.NoContext, code)
	if err != nil {
		log.Fatal(err)
	}

	fmt.Printf("Token: %v\n", tok)

	client := conf.Client(oauth2.NoContext, tok)

	requestBody, err := json.Marshal(nil)
	if err != nil {
		log.Fatal(err)
	}
	resp, err := client.Post("https://api.dropboxapi.com/2/users/get_current_account", "application/json", bytes.NewBuffer(requestBody))
	if err != nil {
		log.Fatal(err)
	}
	fmt.Printf("Status: %v\n", resp.Status)
	responseBody, _ := ioutil.ReadAll(resp.Body)
	fmt.Println("response Body:", string(responseBody))
}
```

If you're still having trouble, maybe you can share your code and the specific error you're seeing.

**Comment by smarx** [comment]
Also, apologies for my Go... I'm really not that familiar with the language and likely made some newbie mistakes here. Please correct any language issues you see!

**Comment by diwakergupta** [comment]
Thanks @smarx!

@joncalhoun feel free to use [dbxcli](https://github.com/dropbox/dbxcli/) as a reference app for this SDK as well, e.g.
https://github.com/dropbox/dbxcli/blob/master/cmd/root.go#L149

**Comment by joncalhoun** [comment]
Thanks @smarx and @diwakergupta.

The example you provided works, and the example in dbxcli works, but in both cases you don't have a redirect URI and I think this is what is missing in the exchange step. Eg:


```go
package main

import (
	"fmt"
	"log"

	"golang.org/x/oauth2"
)

func main() {
	oauth2RedirectURI := oauth2.SetAuthURLParam("redirect_uri", "http://localhost:3000/oauth/dropbox")
	oauth2ResponseType := oauth2.SetAuthURLParam("response_type", "code")
	conf := &oauth2.Config{
		ClientID:     "<REDACTED>",
		ClientSecret: "<REDACTED>",
		Endpoint: oauth2.Endpoint{
			AuthURL:  "https://www.dropbox.com/oauth2/authorize",
			TokenURL: "https://www.dropbox.com/oauth2/token",
		},
	}

	url := conf.AuthCodeURL("use-a-real-state-here", oauth2RedirectURI, oauth2ResponseType)
	fmt.Printf("Visit this URL: %v\n", url)
	fmt.Print("Enter the access code: ")

	// Copy code from URL. My normal code has a handler for the page but in this example i'm just copying it for simplicty.
	var code string
	if _, err := fmt.Scan(&code); err != nil {
		log.Fatal(err)
	}
	tok, err := conf.Exchange(oauth2.NoContext, code)
	if err != nil {
		log.Fatal(err)
	}

	fmt.Printf("Token: %v\n", tok)
}
```


Here is my output:

```
Visit this URL: https://www.dropbox.com/oauth2/authorize?client_id=<REDACTED>&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Foauth%2Fdropbox&response_type=code&state=use-a-real-state-here
Enter the access code: 0hiP2or7-RkAAAAAAABGsRuh4N0c97ECmY_4adtP4xA
2016/05/03 13:16:52 oauth2: cannot fetch token: 400 Bad Request
Response: <!DOCTYPE html>
<html>
<head><title>Dropbox - 400</title>
<link href="//www.dropbox.com/static/css/error.css" rel="stylesheet" type="text/css"/>
<link rel="shortcut icon" href="//www.dropbox.com/static/images/favicon.ico"/>
</head>
<body>
<div class="figure">
<img src="//www.dropbox.com/static/images/sickbox.png" alt="Error: 400"/>
</div>
<div id="errorbox">
<h1>Error (400)</h1>Something went wrong. Don't worry, your files are still safe and the Dropboxers have been notified. Check out our <a href="https://www.dropbox.com/help">Help Center</a> and <a href="https://forums.dropbox.com">forums</a> for help, or head back to <a href="https://www.dropbox.com/home">home</a>.
</div>

</body>
</html>
exit status 1
```

**Comment by smarx** [comment]
Your `TokenURL` looks wrong. Not sure if it can ever work with that domain, but at the very least, it will mask the actual error. (This is why you're getting HTML back.)

**Comment by joncalhoun** [comment]
That was definitely the issue. Sorry to bug you both 😦  For some reason I just assumed it would be the same base, but it makes sense that they aren't.

If you both don't mind I'll push a PR to hopefully prevent others from making the same stupid mistake.
