### ISSUE TITLE
Logging response body

### ISSUE THREAD

**Issue by DexterHaslem** [dropbox/dropbox-sdk-go-unofficial#23]
Verbose logging prints the response body, when downloading a large file, this naturally results in a very large log. Is there any value in this? 

I'm offering to remove it or put it behind a flag if there is a compelling reason to have it

**Comment by diwakergupta** [comment]
@DexterHaslem it's just meant for debugging, so I'm hoping this is not a huge blocker for people. Otherwise yes, some sort of leveled logging probably makes most sense (e.g. how AWS does it: https://github.com/aws/aws-sdk-go/blob/master/aws/logger.go)

**Comment by DexterHaslem** [comment]
OK, I will give it a shot putting it behind some log levels as time permits
