### ISSUE TITLE
Code example for folder listing

### ISSUE THREAD

**Issue by cheebo** [dropbox/dropbox-sdk-go-unofficial#26]
Hi guys, could you please give me the idea how can I get the data from the received list of entries for the folder. all I can see entity has ```IsMetadata``` method and how can I convert it to structs that represents files/folders correct or "extract" data any other way?

My example code works correct (works correct, receive data from dropbox, but only can dump the entity)
```go
import (
    "github.com/dropbox/dropbox-sdk-go-unofficial/dropbox"
    "github.com/dropbox/dropbox-sdk-go-unofficial/dropbox/files"
)
...
dbf := files.New(config)
farg := files.ListFolderArg{}
listFolder, err := dbf.ListFolder(&farg)

for _, entry := range listFolder.Entries {
  // how can I get the data from entry here? 
}
```

**Comment by yodur2potassium** [comment]
A year or so later, same problem... I can't get my head around it. Seems to have no way to get data from the ListFolderResult

**Comment by yodur2potassium** [comment]
Ok, after long and painful hours, I managed to get data. you need to type cast the Entries to be able to handle objects, there is no way to know at compile time wich kind of Metadata it is...
```go
switch metadata.(type) {
	// Casting types to access the metadata
	case *files.FileMetadata:
		// Handles case of file, cast type and create doc
		fileEntry, _ := metadata.(*files.FileMetadata)
		log.Debug("Document found :" + fileEntry.PathLower)
		doc := db.createDocument(*fileEntry)
		// Pass document to the handler function for indexing
		if filter(doc) {
			log.Debug("Handling " + doc.GetPath())
			handler(doc)
		}
...
```

**Comment by yodur2potassium** [comment]
@diwakergupta no worries, I managed to do what I wanted. That was an evolution on an already existing Go app to grap our Dropbox, I just posted the example so if anyone have the same problem can find a clue :smile:
