### ISSUE TITLE
Export appImpl

### ISSUE THREAD

**Issue by mileusna** [dropbox/dropbox-sdk-go-unofficial#31]
Since appImpl structs are not exported it is hard to make a wrapper or to include dbox inside own struct. For example, you can't write something like this.

```go
type MyApp struct {
    db *files.appImpl
}
```

And it is actually bad Go practice for exported functions (i.e. `files.New()`) to return un-exported types (i.e. `files.appImpl`)

**Comment by diwakergupta** [comment]
Please use `files.Client` instead.

Fair point about `New` returning `apiImpl` -- I'll look into changing that. Meanwhile, PRs are welcome!
