### ISSUE TITLE
Could not use batch copy/delete/move operations

### ISSUE THREAD

**Issue by watermint** [dropbox/dropbox-sdk-go-unofficial#32]
Thank you for maintaining great SDK. I found the following issues during implementing mass file operation tool.

# AsyncJobId

Batch operations usually require using AsyncJobId. But there is no AsyncJobId in a response of {Copy|Move|Delete}Batch.
Type *BatchLaunch also don't have AsyncJobId.

# *BatchCheck fail parsing response

I tried only for MoveBatch. When result tag == "complete", MoveBatchCheck fail to parse entities.

**Comment by diwakergupta** [comment]
Thanks for the report. Seems like a bug in the API spec itself?
https://github.com/dropbox/dropbox-api-spec/blob/master/files.stone#L1253

I will double check with the spec authors.

Meanwhile, for the complete issue, can you paste the verbose output when the parsing failure happens?

**Comment by diwakergupta** [comment]
Actually you are right, this is a bug in the SDK, not the spec. I'll look into it, meanwhile please do add the verbose output if you can -- that will help.
