### ISSUE TITLE
Retry-After header not visible to clients

### ISSUE THREAD

**Issue by ncw** [dropbox/dropbox-sdk-go-unofficial#33]
It states in [the data ingress guide](https://www.dropbox.com/developers/reference/data-ingress-guide):

> Rate limited responses include a Retry-After header that provides the duration, in seconds, your app should wait before retrying the request to avoid a subsequent rate limit response. 

Unfortunately these headers are not surfaced by the API.

A typical response looks like this

```
HTTP/1.1 429 too_many_write_operations/.
Transfer-Encoding: chunked
Connection: keep-alive
Content-Type: application/json
Date: Thu, 02 Nov 2017 14:25:01 GMT
Retry-After: 1
Server: nginx
X-Dropbox-Request-Id: XXX
X-Robots-Tag: noindex, nofollow, noimageindex

6c
{"error_summary": "too_many_write_operations/.", "error": {"reason": {".tag": "too_many_write_operations"}}}
0
```

The easiest way to fix this would be to add a `RetryAfter` field to the base APIError struct, eg

```
// APIError is the base type for endpoint-specific errors.
type APIError struct {
	ErrorSummary string `json:"error_summary"`
	RetryAfter time.Duration
}
```

And fill this from the RetryAfter Header if it was found.

This would need quite a bit of patching though so you may have a better idea?

**EDIT**

Though it might actually be preferable to return all the HTTP headers in the struct and just make a method to retrieve RetryAfter...

**Comment by diwakergupta** [comment]
Thanks @ncw , preserving HTTP headers in some generic map might be reasonable. Or we can special case RetryAfter as you suggest. I'll take a look, meanwhile PRs are always welcome :)

**Comment by ncw** [comment]
I just noticed that these retry-after errors are now making it into the JSON response

```
2017/12/10 08:14:43 DEBUG : HTTP RESPONSE (req 0xc4201ad200)
2017/12/10 08:14:43 DEBUG : HTTP/1.1 429 Too Many Requests
Transfer-Encoding: chunked
Connection: keep-alive
Content-Disposition: attachment; filename='error'
Content-Security-Policy: sandbox; frame-ancestors 'none'
Content-Type: application/json
Date: Sun, 10 Dec 2017 07:00:00 GMT
Retry-After: 300
Server: nginx
X-Content-Type-Options: nosniff
X-Dropbox-Request-Id: XXX
X-Frame-Options: DENY

71
{"error_summary": "too_many_requests/..", "error": {"reason": {".tag": "too_many_requests"}, "retry_after": 300}}
0
```

Does that mean "retry_after" will be available as a Tag on the error now?

**Comment by diwakergupta** [comment]
@ncw interesting. Either way, I agree exposing these in some way is reasonable -- whether that information comes from the HTTP header or the JSON body is more of an implementation detail.

**Comment by mathieucarbou** [comment]
@ncw @diwakergupta : where we are with this issue ? It's been a while and doesn't seem so hard to fix...

**Comment by mathieucarbou** [comment]
Hi again guys,
I have just sent a PR that I was able to successfully test:
https://github.com/dropbox/dropbox-sdk-go-unofficial/pull/46

**Comment by Robot72** [comment]
Can you help me? 
How can I fix it? 
I see this error from productive (this is console script for uploading only one file)
But if I run it from my laptop it works fine
<img width="849" alt="Screenshot 2021-11-10 at 15 17 18" src="https://user-images.githubusercontent.com/5987937/141129720-47ed1d1b-2568-4fd8-adbf-2ad84de17ea8.png">

**Comment by Robot72** [comment]
I've spent much time and didn't found any strong reason in dropbox documentation. Only one script to upload this file in one time but I see this error

**Comment by rajatgoel** [comment]
This error usually means too many concurrent writes are happening to same namespace. 

Btw this server side error has nothing to do with SDK. Probably a better question for https://www.dropboxforum.com/?
