### ISSUE TITLE
500 server errors causing "unexpected end of JSON input" errors

### ISSUE THREAD

**Issue by ncw** [dropbox/dropbox-sdk-go-unofficial#36]
For example during a multipart upload I got this

```
2017/11/20 22:09:15 DEBUG : HTTP REQUEST (req 0xc42adc2d00)
2017/11/20 22:09:15 DEBUG : POST /2/files/upload_session/append_v2 HTTP/1.1
Host: content.dropboxapi.com
User-Agent: rclone/v1.38-167-g49a9a817-dump-response
Content-Length: 0
Authorization: XXXX
Content-Type: application/octet-stream
Dropbox-Api-Arg: {"cursor":{"session_id":"AAAAAAAAswW3y5-Q1EPD7Q","offset":6979321856},"close":false}
Accept-Encoding: gzip
```

```
2017/11/20 22:09:34 DEBUG : HTTP RESPONSE (req 0xc42adc2d00)
2017/11/20 22:09:34 DEBUG : HTTP/1.1 500 Internal Server Error
Transfer-Encoding: chunked
Connection: keep-alive
Content-Type: text/plain; charset=utf-8
Date: Mon, 20 Nov 2017 22:09:34 GMT
Server: nginx
X-Dropbox-Request-Id: 9c5973e7e695c0ec4d6747ebbb2ca679
X-Robots-Tag: noindex, nofollow, noimageindex

0
```

This error was returned by the SDK

```
unexpected end of JSON input
```

Indicating that the SDK tried to parse the result of the 500 error response.

**Comment by diwakergupta** [comment]
@ncw thanks for the report. Can you reproduce this with `LogLevel.LogDebug`? That should spit out the full body of the response, and will help me debug the SDK. Thanks!

**Comment by ncw** [comment]
I included the full body of the response above - there wasn't one!

**Comment by diwakergupta** [comment]
Heh. Well, I did look around and you're right, the SDK needs to have additional handling for 500 errors, similar to the Python SDK:

https://github.com/dropbox/dropbox-sdk-python/blob/3f109f5a88badb684d39a4eb1909abedafa603f8/dropbox/dropbox.py#L413

**Comment by diwakergupta** [comment]
@ncw BTW do you have a reliable way of reproducing this? I'm trying to figure out a good way to test any fix I do.

**Comment by ncw** [comment]
Err, I had about 4 of these when uploading about 2 TB of files with rclone. So reproducable, but not very straight forward!

I have a little shell script you could use with rclone if you want?

**Comment by ncw** [comment]
Here is my shell script.  You'll need to [set up rclone to point to a dropbox account](https://rclone.org/dropbox/)

Note that the easiest way to test rclone with your changes is to move `vendor/dropbox/dropbox-sdk-go-unofficial` out of the way temporarily, then do a `go install` otherwise rclone will just use the vendored version.

```shell
#!/bin/bash

size=1G
count=1000

rm -rf bigfiles
mkdir -p bigfiles

./rclone -vv mkdir dropbox:bigfiles
./rclone -vv delete dropbox:bigfiles

for i in `seq -w 1 ${count}`; do

    dd if=/dev/zero of=bigfiles/bigfile$i bs=1 seek=${size} count=1

done

./rclone --transfers 16 -vv --stats 10s --dump responses --retries 1 copy bigfiles dropbox:bigfiles 2>&1 | tee bigfile-`date -Is`.log
}}}

**Comment by diwakergupta** [comment]
@ncw I'm pushing a change that should at least properly parse the error and give you a real `APIError` response. Unfortunately, I can't do much about the internal server errors themselves; they can and will continue to happen :-/ LMK if that helps.

**Comment by ncw** [comment]
@diwakergupta I've had a recurrence of this issue in https://github.com/ncw/rclone/issues/2158 which turns out to be a 503 error, so I think this fix might need to be more robust.

That issue is about uploading huge files (380GB) to dropbox Enterprise, and the final `/2/files/upload_session/finish` returning `503 Service Unavailable` with an empty body.

I'd really appreciate it if you have time to have a look through that issue and give an opinion on whether the UploadSessionFinish will ever work with a file so big or whether rclone should be using UploadSessionFinishBatch or whether there is a better way - thanks.
