### ISSUE TITLE
users.Client.GetCurrentAccount() no longer works

### ISSUE THREAD

**Issue by DexterHaslem** [dropbox/dropbox-sdk-go-unofficial#38]
It looks like something changed in the response and a json unmarshal error occurs here:

users/client.go 226

Struct = FullAccount
Field = root_info

**Comment by diwakergupta** [comment]
@DexterHaslem thanks for the report, I can reproduce this. Investigating.

**Comment by diwakergupta** [comment]
Alright, I think I know the problem. Will push a fix probably over the weekend.

**Comment by DexterHaslem** [comment]
Great, appreciate it!
