### ISSUE TITLE
users.GetSpaceUsage() allocation no longer populated

### ISSUE THREAD

**Issue by DexterHaslem** [dropbox/dropbox-sdk-go-unofficial#39]
Hi again,
after some recent changes users.GetSpaceUsage() response seems to always leave Allocation properties (team and individual) nil. Just wanted to let you know this was previously working fine

**Comment by diwakergupta** [comment]
@DexterHaslem how are you reproducing this? Testing via `dbxcli du` still seems to work for me.

**Comment by DexterHaslem** [comment]
Hi, users client is actually giving me several problems now. In the GetCurrentAccount() response, name is always nil and rest of fields like email are empty, this used to be populated too. Here is how I'm reproducing, generated token or a legit one from oauth flow have same problem. Just plop a good token in here:

```go
package main

import (
	"fmt"

	db "github.com/dropbox/dropbox-sdk-go-unofficial/dropbox"
	dbUsers "github.com/dropbox/dropbox-sdk-go-unofficial/dropbox/users"
)

func main() {

	c := db.Config{Token: "<ADDTOKEN>", LogLevel: db.LogInfo}
	u := dbUsers.New(c)

	ca, err := u.GetCurrentAccount()
	if err == nil {
		fmt.Printf("GetCurrentAccount: name: %s email: %s", ca.Name, ca.Email)
	} else {
		fmt.Printf("GetCurrentAccount err: %s", err.Error())
	}

	su, err := u.GetSpaceUsage()
	if err == nil {
		fmt.Printf("GetSpaceUsage: allocation: %+v", su.Allocation)
	} else {
		fmt.Printf("GetSpaceUsage err: %s", err.Error())
	}
}
```

I just did go get -u -v github.com/dropbox/dropbox-sdk-go-unofficial/dropbox to make sure no stale deps but no changes. Let me know if you can reproduce with this simple litmus!

**Comment by diwakergupta** [comment]
Yes, I'm aware of the `GetCurrentAccount` issue (e.g. `dbxcli account` is crashing right now :( ). So I'm good on the test cases, will try to provide a fix over the holidays!
