### ISSUE TITLE
Where to obtain a token.

### ISSUE THREAD

**Issue by bweston92** [dropbox/dropbox-sdk-go-unofficial#42]
I want to use this for personal use, I don't need an "app" just the ability to upload pictures via the API.

How would I go about getting a token to do that?

Cannot find anything here: https://www.dropbox.com/developers

**Comment by DexterHaslem** [comment]
you still need to create an 'app' on your personal account. it will create a personal token representing your account you can use without having to go through oauth flow

**Comment by bweston92** [comment]
Thanks, sorry I forgot to close the issue once resolved.
