### ISSUE TITLE
What is the best way to view files in non default namespaces?

### ISSUE THREAD

**Issue by ncw** [dropbox/dropbox-sdk-go-unofficial#45]
I'm trying to use namespaces to read users team drives.  I'm using the `users.GetCurrentAccount()` to get the namespaces. 

I read in [the docs](https://www.dropbox.com/developers/reference/namespace-guide#nspaths) that I can use an `ns:` prefix (eg  `ns:12345`) on the path.  However this doesn't seem to work :-(

I don't know whether this is me doing something stupid or not, but I I opened [this query](https://www.dropboxforum.com/t5/API-Support-Feedback/Can-t-get-path-with-ns-prefix-to-work-in-2-files-list-folder/m-p/277821#M16638) on the developer API forum with some plain curl examples.  The equivalents using this SDK don't seem to work either.

However using the `Dropbox-API-Path-Root:` header does seem to work.  I can set this using the `dropbox.Config.HeaderGenerator` however that seems like it probably isn't the intended way!

```go
	config := dropbox.Config{
		HeaderGenerator: func(hostType string, style string, namespace string, route string) map[string]string {
			return map[string]string{
				"Dropbox-API-Path-Root": `{".tag": "namespace_id", "namespace_id": "12345"}`,
			}
		},
	}
```

Anyway, apologies in advance if there is a really obvious answer to this question that I've missed!

**Comment by ncw** [comment]
I've had clarification on the forum that the `ns:` prefix does not work with the team space root ID, so it is the `Dropbox-API-Path-Root:` header or nothing.

I've implemented the code wth the `HeaderGenerator` and it seems to work fine.  Is there a better way of doing it?

THanks

**Comment by aaronstaley** [comment]
Unfortunately this SDK doesn't natively support this feature. You are supposed to modify the headers per https://www.dropbox.com/developers/reference/namespace-guide

The Python SDK for instance has this built in:
https://github.com/dropbox/dropbox-sdk-python/blob/209bf39ae9dc61c1bf3e83433aa5ef7d7eb84cad/dropbox/dropbox.py#L526
