### ISSUE TITLE
unexpected end of input error for DeleteV2

### ISSUE THREAD

**Issue by ts2909** [dropbox/dropbox-sdk-go-unofficial#47]
The SDK appears to be calling the v1 endpoint, instead of v2. If I change the endpoint manually it works. Also appears to the same for Move/Copy

2018/11/16 19:16:21 arg: &{/test }
2018/11/16 19:16:21 req: &{POST https://api.dropboxapi.com/2/files/delete HTTP/1.1 1 1 map[Content-Type:[application/json]] {0xc0001ba270} 0x6498a0 16 [] false api.dropboxapi.com map[] map[] <nil> map[]   <nil> <nil> <nil> <nil>}

// This should be delete_v2?
Line 1276 of ~/go/src/github.com/dropbox/dropbox-sdk-go-unofficial/dropbox/files/client.go
	req, err := (*dropbox.Context)(dbx).NewRequest("api", "rpc", true, "files", "delete", headers, bytes.NewReader(b))

**Comment by diwakergupta** [comment]
@ts2909 this should be fixed in HEAD, can you try again?
