### ISSUE TITLE
Please set tag before breaking changes

### ISSUE THREAD

**Issue by watermint** [dropbox/dropbox-sdk-go-unofficial#5]
I know it's unofficial and unsupported version of SDK. But if it possible, please tag versions before breaking changes.

**Comment by diwakergupta** [comment]
@watermint thanks for the feedback, yes this is definitely the desired direction. I'm still figuring out how best to version the SDK (and how to encode the version within the SDK itself). As soon as I have a clear direction, I will start tagging releases.
