### ISSUE TITLE
UploadSessionFinishBatch endpoint does not work

### ISSUE THREAD

**Issue by dchesterton** [dropbox/dropbox-sdk-go-unofficial#6]
The UploadSessionFinishBatch endpoint does not work. This is due to CommitInfo.ClientModified's default value being 0001-01-01 00:00:00 +0000 UTC. Setting ClientModified to the current time does not work either as the generated JSON includes milliseconds which the API rejects.

Setting ClientModified to be a pointer to time.Time fixes the first issue but not the second.

**Comment by diwakergupta** [comment]
@dchesterton can you include the full stack trace with sample code that shows how you are using the API? that will help me repro and fix. Thanks for the report!

**Comment by diwakergupta** [comment]
I think I know what might be going on here. The Dropbox API expects UTC timestamps and doesn't support fractional seconds (https://github.com/dropbox/dropbox-api-spec/blob/master/common.stone#L3). You can see how `dbxcli` supplies the timestamp here: https://github.com/dropbox/dbxcli/blob/master/cmd/put.go#L102  Basically something like this should work:

```go
commitInfo.ClientModified = time.Now().UTC().Round(time.Second)
```

Please reopen if this doesn't fix your issue
