### ISSUE TITLE
error returned by files.Download unhelpful when response body is blank

### ISSUE THREAD

**Issue by shasderias** [dropbox/dropbox-sdk-go-unofficial#64]
When an invalid path is provided (e.g. "asdf.csv") as the path to a files.Download call, the returned APIError has an empty string as its ErrorSummary.

I.e. this:
``` Go
result, content, err := c.files.Download(files.NewDownloadArg("asdf.csv"))
fmt.Println(err)
```
prints nothing.

The returned error is fine when a valid path is provided, but no file exists at that path ("path/not_found/..." is printed in this case)

Relevant code located at files/client.go:1693, which calls sdk.go:212.

A little digging suggests that this is due to the response body being empty. However, https://www.dropbox.com/developers/documentation/http/documentation#error-handling suggests that in the case of a 400 Bad Request status code, "The response body is a plaintext message with more information.".

This might be more properly fixed server side. However, perhaps APIError should also hold the response code, and in the case where ErrorSummary is blank, stringify into the response code plus a short error message instead?

**Comment by rajatgoel** [comment]
#87 fixes this. It will be part of next release.
