### ISSUE TITLE
Travis job failed in Intel

### ISSUE THREAD

**Issue by kishorkunal-raj** [dropbox/dropbox-sdk-go-unofficial#65]
Hi All,
I am using Travis-CI to run jobs on Intel architecture but all the jobs are failing stating "Package not found". Logs are below

$ git submodule update --init --recursive

0.01s5.33s$ travis_setup_go

go version go1.9.7 linux/amd64

$ export GOPATH="/home/travis/gopath"

$ export PATH="/home/travis/gopath/bin:/home/travis/.gimme/versions/go1.9.7.linux.amd64/bin:/home/travis/bin:/home/travis/bin:/home/travis/.local/bin:/usr/local/lib/jvm/openjdk11/bin:/opt/pyenv/shims:/home/travis/.phpenv/shims:/home/travis/perl5/perlbrew/bin:/home/travis/.nvm/versions/node/v8.12.0/bin:/home/travis/.rvm/gems/ruby-2.5.3/bin:/home/travis/.rvm/gems/ruby-2.5.3@global/bin:/home/travis/.rvm/rubies/ruby-2.5.3/bin:/home/travis/gopath/bin:/home/travis/.gimme/versions/go1.11.1.linux.amd64/bin:/usr/local/maven-3.6.3/bin:/usr/local/cmake-3.12.4/bin:/usr/local/clang-7.0.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/home/travis/.rvm/bin:/home/travis/.phpenv/bin:/opt/pyenv/bin:/home/travis/.yarn/bin"

$ export GO111MODULE="auto"

$ gimme version

v1.5.4

$ go version

go version go1.9.7 linux/amd64
go.env

$ go env
install

2.64s$ go get -u golang.org/x/oauth2

0.00s$ set -e

The command "set -e" exited with 0.

$ GOOS=linux   GOARCH=amd64 go install ./dropbox/...

dropbox/async/types.go:27:2: cannot find package "github.com/dropbox/dropbox-sdk-go-unofficial/dropbox" in any of:

	/home/travis/.gimme/versions/go1.9.7.linux.amd64/src/github.com/dropbox/dropbox-sdk-go-unofficial/dropbox (from $GOROOT)

	/home/travis/gopath/src/github.com/dropbox/dropbox-sdk-go-unofficial/dropbox (from $GOPATH)

dropbox/contacts/client.go:30:2: cannot find package "github.com/dropbox/dropbox-sdk-go-unofficial/dropbox/auth" in any of:

	/home/travis/.gimme/versions/go1.9.7.linux.amd64/src/github.com/dropbox/dropbox-sdk-go-unofficial/dropbox/auth (from $GOROOT)

	/home/travis/gopath/src/github.com/dropbox/dropbox-sdk-go-unofficial/dropbox/auth (from $GOPATH)

dropbox/files/client.go:32:2: cannot find package "github.com/dropbox/dropbox-sdk-go-unofficial/dropbox/async" in any of:

	/home/travis/.gimme/versions/go1.9.7.linux.amd64/src/github.com/dropbox/dropbox-sdk-go-unofficial/dropbox/async (from $GOROOT)

	/home/travis/gopath/src/github.com/dropbox/dropbox-sdk-go-unofficial/dropbox/async (from $GOPATH)

dropbox/files/client.go:34:2: cannot find package "github.com/dropbox/dropbox-sdk-go-unofficial/dropbox/file_properties" in any of:

	/home/travis/.gimme/versions/go1.9.7.linux.amd64/src/github.com/dropbox/dropbox-sdk-go-unofficial/dropbox/file_properties (from $GOROOT)

	/home/travis/gopath/src/github.com/dropbox/dropbox-sdk-go-unofficial/dropbox/file_properties (from $GOPATH)

dropbox/paper/types.go:30:2: cannot find package "github.com/dropbox/dropbox-sdk-go-unofficial/dropbox/sharing" in any of:

	/home/travis/.gimme/versions/go1.9.7.linux.amd64/src/github.com/dropbox/dropbox-sdk-go-unofficial/dropbox/sharing (from $GOROOT)

	/home/travis/gopath/src/github.com/dropbox/dropbox-sdk-go-unofficial/dropbox/sharing (from $GOPATH)

dropbox/sharing/types.go:30:2: cannot find package "github.com/dropbox/dropbox-sdk-go-unofficial/dropbox/files" in any of:

	/home/travis/.gimme/versions/go1.9.7.linux.amd64/src/github.com/dropbox/dropbox-sdk-go-unofficial/dropbox/files (from $GOROOT)

	/home/travis/gopath/src/github.com/dropbox/dropbox-sdk-go-unofficial/dropbox/files (from $GOPATH)

dropbox/sharing/types.go:31:2: cannot find package "github.com/dropbox/dropbox-sdk-go-unofficial/dropbox/seen_state" in any of:

	/home/travis/.gimme/versions/go1.9.7.linux.amd64/src/github.com/dropbox/dropbox-sdk-go-unofficial/dropbox/seen_state (from $GOROOT)

	/home/travis/gopath/src/github.com/dropbox/dropbox-sdk-go-unofficial/dropbox/seen_state (from $GOPATH)

dropbox/sharing/types.go:32:2: cannot find package "github.com/dropbox/dropbox-sdk-go-unofficial/dropbox/team_common" in any of:

	/home/travis/.gimme/versions/go1.9.7.linux.amd64/src/github.com/dropbox/dropbox-sdk-go-unofficial/dropbox/team_common (from $GOROOT)

	/home/travis/gopath/src/github.com/dropbox/dropbox-sdk-go-unofficial/dropbox/team_common (from $GOPATH)

dropbox/sharing/types.go:33:2: cannot find package "github.com/dropbox/dropbox-sdk-go-unofficial/dropbox/users" in any of:

	/home/travis/.gimme/versions/go1.9.7.linux.amd64/src/github.com/dropbox/dropbox-sdk-go-unofficial/dropbox/users (from $GOROOT)

	/home/travis/gopath/src/github.com/dropbox/dropbox-sdk-go-unofficial/dropbox/users (from $GOPATH)

dropbox/team/types.go:31:2: cannot find package "github.com/dropbox/dropbox-sdk-go-unofficial/dropbox/team_policies" in any of:

	/home/travis/.gimme/versions/go1.9.7.linux.amd64/src/github.com/dropbox/dropbox-sdk-go-unofficial/dropbox/team_policies (from $GOROOT)

	/home/travis/gopath/src/github.com/dropbox/dropbox-sdk-go-unofficial/dropbox/team_policies (from $GOPATH)

dropbox/team_log/types.go:31:2: cannot find package "github.com/dropbox/dropbox-sdk-go-unofficial/dropbox/team" in any of:

	/home/travis/.gimme/versions/go1.9.7.linux.amd64/src/github.com/dropbox/dropbox-sdk-go-unofficial/dropbox/team (from $GOROOT)

	/home/travis/gopath/src/github.com/dropbox/dropbox-sdk-go-unofficial/dropbox/team (from $GOPATH)

dropbox/users/types.go:29:2: cannot find package "github.com/dropbox/dropbox-sdk-go-unofficial/dropbox/common" in any of:

	/home/travis/.gimme/versions/go1.9.7.linux.amd64/src/github.com/dropbox/dropbox-sdk-go-unofficial/dropbox/common (from $GOROOT)

	/home/travis/gopath/src/github.com/dropbox/dropbox-sdk-go-unofficial/dropbox/common (from $GOPATH)

dropbox/users/types.go:32:2: cannot find package "github.com/dropbox/dropbox-sdk-go-unofficial/dropbox/users_common" in any of:

	/home/travis/.gimme/versions/go1.9.7.linux.amd64/src/github.com/dropbox/dropbox-sdk-go-unofficial/dropbox/users_common (from $GOROOT)

	/home/travis/gopath/src/github.com/dropbox/dropbox-sdk-go-unofficial/dropbox/users_common (from $GOPATH)
=============

Please look into it.

**Comment by rajatgoel** [comment]
Hi @kishorkunal-raj, we have dropped support for Go 1.9 and recently updated the package to use Go modules. 

Please give it a try and open a new ticket if it still fails.
