### ISSUE TITLE
Is there any plan to release a new version?

### ISSUE THREAD

**Issue by Xuanwo** [dropbox/dropbox-sdk-go-unofficial#77]
**Before you start**

No

**What is your question?**

Is there any plan to release a new version?

**Versions**
* What version of the SDK are you using? 
v5.6.0
* What version of the language are you using?
golang 1.15
* What platform are you using? (if applicable)
N/A

---

We use this sdk in https://github.com/aos-dev/go-service-dropbox/pull/12#discussion_r621941792 , and we want to track on stable release instead of git version.

And we want to include features like both `UploadSessionTypeSequential` and `UploadSessionTypeConcurrent`.

**Comment by JinnyYi** [comment]
I have to perform a cast when calling `DeleteV2`. Seems that `DeleteV2APIError` is an error-wrapper for the `DeleteV2` route.
But when I tried to cast the error to `DeleteV2APIError` it failed, and change the type to `DeleteAPIError` it works.

I noticed that the code online has been updated in https://github.com/dropbox/dropbox-sdk-go-unofficial/blob/master/dropbox/files/client.go#L1444. Is there any plan to release a new version?

**Comment by rajatgoel** [comment]
@diwakergupta are there any instructions on how to release a new version? I am guessing with introduction of Go modules we should tag next release as v6.0.0?

**Comment by rajatgoel** [comment]
Well apparently this won't work. Go modules require version to be v0 or v1 and we were already at version 5.6.0. Any ideas how to solve this problem?

**Comment by Xuanwo** [comment]
If version is bigger than v1, we should append version suffix after module name like

```go
module github.com/dropbox/xxxx/v6
```

**Comment by gwatts** [comment]
for my 2 cents (if worth that!)  - I'd keep the version numbering consistent, and add the `v6` suffix per @Xuanwo suggestion and just update the docs to reflect that that's what people should use to get the latest version.

**Comment by rajatgoel** [comment]
@gwatts Sounds good. 

If one of you can take a quick look at #80 and confirm this is correct, I will merge this and tag this new commit as v6.0.1? That should be it?
